name       : gnome-mahjongg
version    : 3.36.1
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-mahjongg/3.36/gnome-mahjongg-3.36.1.tar.xz : ed7758cf77cc7d8ec27459a415a842ab56b3ad371547e1cd58ea825c5529b0a8
license    : GPL-2.0-or-later
component  : games.card
summary    : Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
