name       : gnome-mahjongg
version    : 3.32.0
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-mahjongg/3.32/gnome-mahjongg-3.32.0.tar.xz : 52843745a17ef1e9e80820432b3317aa885ec7417ac1e9239946c0d56daf6a8a
license    : GPL-2.0-or-later
component  : games.card
summary    : Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
