name       : gnome-mahjongg
version    : 3.20.0
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-mahjongg/3.20/gnome-mahjongg-3.20.0.tar.xz : d09bb1923636dfd05b6f3a5af8d6fe7b6daa1434e2c06188dd27c96a61cea00a
license    : GPL-2.0
component  : games.card
summary    : Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
description: |
    Mahjongg is a solitaire (one player) version of the classic Eastern tile game, Mahjongg.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
